# Generated by Django 2.2.4 on 2019-08-15 05:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('web_address', models.URLField(blank=True, max_length=150, null=True)),
                ('cover_letter', models.TextField(blank=True, default='', null=True)),
                ('attachment', models.FileField(default='', upload_to='')),
                ('working', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField(null=True, protocol='IPv4')),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
