# Generated by Django 2.2.4 on 2019-08-16 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geospoc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
    ]
